name: Java CI com Maven

on:
  push:
    branches:
      - homolog
  pull_request:
    branches:
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Exibir versão do Java
        run: java -version

      - name: Construir com Maven
        run: mvn clean install

      - name: Executar testes com Maven
        run: mvn test
